# Generated by Django 3.0.4 on 2020-08-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200518_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='created_at',
            new_name='bookedat',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='urlid',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='city',
            new_name='pno',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='add',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='link',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='country',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='url',
            name='dom',
        ),
        migrations.RemoveField(
            model_name='url',
            name='domage',
        ),
        migrations.RemoveField(
            model_name='url',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='url',
            name='ipadd',
        ),
        migrations.RemoveField(
            model_name='url',
            name='ipcity',
        ),
        migrations.RemoveField(
            model_name='url',
            name='ipcountry',
        ),
        migrations.RemoveField(
            model_name='url',
            name='iplatitude',
        ),
        migrations.RemoveField(
            model_name='url',
            name='iplongitude',
        ),
        migrations.RemoveField(
            model_name='url',
            name='ipstate',
        ),
        migrations.RemoveField(
            model_name='url',
            name='org',
        ),
        migrations.RemoveField(
            model_name='url',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='url',
            name='redir',
        ),
        migrations.RemoveField(
            model_name='url',
            name='registrar',
        ),
        migrations.RemoveField(
            model_name='url',
            name='state',
        ),
        migrations.RemoveField(
            model_name='url',
            name='var3',
        ),
        migrations.RemoveField(
            model_name='url',
            name='var5',
        ),
        migrations.RemoveField(
            model_name='url',
            name='varab',
        ),
    ]
