# Generated by Django 3.0.4 on 2020-08-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200828_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='created_at',
            new_name='bookedat',
        ),
    ]
