# Generated by Django 3.0.4 on 2020-08-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200828_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='bookedat',
            new_name='created_at',
        ),
    ]
