# Generated by Django 3.0.4 on 2020-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20200828_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='name',
            field=models.CharField(default='Not Found', max_length=1000, null=True),
        ),
    ]
